### ISSUE TITLE
Party roles not displayed in frame.

### ISSUE THREAD

**Issue by Odysseas68** [Hyphie24/ShadowedUnitFrames-Mists#30]
Hi and thanks for the updates. 

I notice that when I'm in a party the roles/icons (Healer/Tank/DPS) of members does not displayed in frame. I have enable the `Raid role` indicator and i have position it at bottom right like Retail.

**Comment by Odysseas68** [comment]
There are no LUA errors. If you unlock the frames you can see the indicator but when locked no icon appear. I haven't test is in a raid to see.

**Comment by Odysseas68** [comment]
Ok i fix it. In `modules/indicators.lua` Line 1 replace it with:

`local Indicators = {list = {"status", "pvp", "leader", "resurrect", "masterLoot", "raidTarget", "ready", "role", "lfdRole", "class", "phase", "happiness" }}`

after the world `"role"` i add the `"lfdRole"`

i found a commit https://github.com/Nevcairiel/ShadowedUnitFrames/pull/39/commits/eb6cd0df73e1e247ef6401311ae8236c3570c0e7

**Comment by Hyphie24** [comment]
Should be fixed with https://github.com/Hyphie24/ShadowedUnitFrames-Mists/pull/25/commits/e4a67f46f758673e990ae301c02ca488ca08159a

**Comment by pokbot6** [comment]
still doesnt seem to work, i have tried all: player/party/raid

neither class role or raid role shows up on the unit frame

**Comment by Hyphie24** [comment]
odd, I put in the way as above it should've

**Comment by Odysseas68** [comment]
> still doesnt seem to work, i have tried all: player/party/raid
> 
> neither class role or raid role shows up on the unit frame

Have you enable in `Party --> Indicators --> Raid Role` ? 
Also anchor point set it to `Bottom Right` so you can see it and not overlap with other icons.
Also check if you have the latest release from this channel. Delete the old 2 folders, download the new zip and copy the 2 folders to your addons directory.
